version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo Installing Java and Maven
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  build:
    commands:
      - echo Build started
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn deploy
artifacts:
  files:
    - target/yahtzee-0.0.1-SNAPSHOT.jar