version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn deploy
artifacts:
  files:
    - target/yahtzee-0.0.1-SNAPSHOT.jar